url: "https://diaspora.github.io" # the base hostname & protocol
baseurl: "/diaspora_federation" # the subpath

exclude:
  - .*
  - LICENSE

sass:
  sass_dir: assets/css
  style: nested
  deploy_style: nested

kramdown:
  toc_levels: 2..2

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
